package org.metaforms.forms.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Forms_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("a92871fa-5f1a-445a-984b-c1a961bd4e82(org.metaforms.forms)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
