package org.metaforms.forms.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum OrientationEnum {
  horizontal("\u0433\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u0430\u044f", "horizontal"),
  vertical("\u0432\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f", "vertical");

  private String myName;
  private String myValue;

  OrientationEnum(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

  public static List<OrientationEnum> getConstants() {
    List<OrientationEnum> list = ListSequence.fromList(new LinkedList<OrientationEnum>());
    ListSequence.fromList(list).addElement(OrientationEnum.horizontal);
    ListSequence.fromList(list).addElement(OrientationEnum.vertical);
    return list;
  }

  public static OrientationEnum getDefault() {
    return OrientationEnum.horizontal;
  }

  public static OrientationEnum parseValue(String value) {
    if (value == null) {
      return OrientationEnum.getDefault();
    }
    if (value.equals(OrientationEnum.horizontal.getValueAsString())) {
      return OrientationEnum.horizontal;
    }
    if (value.equals(OrientationEnum.vertical.getValueAsString())) {
      return OrientationEnum.vertical;
    }
    return OrientationEnum.getDefault();
  }
}
