package org.metaforms.forms.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.WeavingMappingRuleContext;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_1597384487797204855(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797204832(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id") + "Panel";
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083689(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083698(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "CreditClass" + SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083715(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083736(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "Document" + SPropertyOperations.getString(_context.getNode(), "id") + "Dao";
  }

  public static Object propertyMacro_GetPropertyValue_4331940832032835624(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083776(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083801(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "Document" + SPropertyOperations.getString(_context.getNode(), "id") + "Model";
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083819(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083837(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "set" + SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083853(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797083867(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_1597384487797205626(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "frame");
  }

  public static Object propertyMacro_GetPropertyValue_1842983950098423420(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("createPanel", SNodeOperations.getContainingRoot(_context.getNode()));
  }

  public static Object referenceMacro_GetReferent_1597384487797204802(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "documentReference", true), "document", false), "documentModelLabel");
  }

  public static Object referenceMacro_GetReferent_1842983950098444827(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "container", true), "createContainerLabel");
  }

  public static Object referenceMacro_GetReferent_1597384487797185496(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "documentDAOLabel");
  }

  public static boolean ifMacro_Condition_1842983950098518174(final IOperationContext operationContext, final IfMacroContext _context) {
    return false;
  }

  public static Iterable sourceNodesQuery_1597384487797083722(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "field", true);
  }

  public static Iterable sourceNodesQuery_4331940832032799663(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "field", true);
  }

  public static Iterable sourceNodesQuery_1597384487797083793(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "field", true);
  }

  public static Iterable sourceNodesQuery_1597384487797083830(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "field", true);
  }

  public static Iterable sourceNodesQuery_1597384487797083860(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "field", true);
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_1597384487797204895(final IOperationContext opereationContext, final WeavingMappingRuleContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel((SNode) SNodeOperations.getParent(_context.getNode()), "formLabel");
  }
}
