package org.metaforms.sandbox;

/*Generated by MPS */

import com.extjs.gxt.ui.client.widget.LayoutContainer;
import com.google.gwt.user.client.Element;
import com.extjs.gxt.ui.client.widget.HorizontalPanel;
import com.extjs.gxt.ui.client.widget.form.FormPanel;
import com.google.gwt.user.client.ui.Widget;
import com.extjs.gxt.ui.client.binding.FormBinding;

public class AdressFormPanel extends LayoutContainer {
  private static String name = "\u0410\u0434\u0440\u0435\u0441";

  private DocumentAdressModel myDocument;

  public AdressFormPanel() {
  }

  @Override
  protected void onRender(Element element, int index) {
    super.onRender(element, index);
    HorizontalPanel hp = new HorizontalPanel();
    hp.setSpacing(10);

    FormPanel panel;
    panel = this.createPanel_87s46c_a();

    // An issue in MPS - need typecast 
    hp.add((Widget) panel);

    FormBinding binding = new FormBinding(panel);
    binding.autoBind();

    add(hp);
  }

  protected FormPanel createPanel_87s46c_a() {
    FormPanel panel = new FormPanel();
    panel.setFrame(false);
    return panel;
  }

  public DocumentAdressModel getDocument() {
    return this.myDocument;
  }

  private void setDocument(DocumentAdressModel value) {
    this.myDocument = value;
  }
}
