package org.metaforms.sandbox;

/*Generated by MPS */

import com.extjs.gxt.ui.client.data.BaseModel;

public class DocumentClientModel extends BaseModel {
  public DocumentClientModel() {
    set("Name", "");
    set("BranchCode", "");
    set("BRANCH", "");
    set("OfficeCode", "");
    set("OfficeName", "");
    set("PointCode", "");
    set("POINT", "");
    set("CEPERSONCODE", "");
    set("CEPERSONNAME", "");
    set("REQTYPECODE", "");
    set("REQTYPE", "");
    set("CREDITNAME", "");
    set("CREDITCURRENCY", "");
    set("CLIENTTYPE", "");
    set("POSITIONTYPE", "");
    set("POSITIONDOC", "");
    set("CURWORKEXPDOC", "");
    set("FULLEXPY", "");
    set("FULLEXPM", "");
    set("CURWORKEXPY", "");
    set("CURWORKEXPM", "");
  }

  public void setName(String value) {
    set("Name", value);
  }

  public void setBranchCode(String value) {
    set("BranchCode", value);
  }

  public void setBRANCH(String value) {
    set("BRANCH", value);
  }

  public void setOfficeCode(String value) {
    set("OfficeCode", value);
  }

  public void setOfficeName(String value) {
    set("OfficeName", value);
  }

  public void setPointCode(String value) {
    set("PointCode", value);
  }

  public void setPOINT(String value) {
    set("POINT", value);
  }

  public void setCEPERSONCODE(String value) {
    set("CEPERSONCODE", value);
  }

  public void setCEPERSONNAME(String value) {
    set("CEPERSONNAME", value);
  }

  public void setREQTYPECODE(String value) {
    set("REQTYPECODE", value);
  }

  public void setREQTYPE(String value) {
    set("REQTYPE", value);
  }

  public void setCREDITNAME(String value) {
    set("CREDITNAME", value);
  }

  public void setCREDITCURRENCY(String value) {
    set("CREDITCURRENCY", value);
  }

  public void setCLIENTTYPE(String value) {
    set("CLIENTTYPE", value);
  }

  public void setPOSITIONTYPE(String value) {
    set("POSITIONTYPE", value);
  }

  public void setPOSITIONDOC(String value) {
    set("POSITIONDOC", value);
  }

  public void setCURWORKEXPDOC(String value) {
    set("CURWORKEXPDOC", value);
  }

  public void setFULLEXPY(String value) {
    set("FULLEXPY", value);
  }

  public void setFULLEXPM(String value) {
    set("FULLEXPM", value);
  }

  public void setCURWORKEXPY(String value) {
    set("CURWORKEXPY", value);
  }

  public void setCURWORKEXPM(String value) {
    set("CURWORKEXPM", value);
  }

  public String getName() {
    return get("Name");
  }

  public String getBranchCode() {
    return get("BranchCode");
  }

  public String getBRANCH() {
    return get("BRANCH");
  }

  public String getOfficeCode() {
    return get("OfficeCode");
  }

  public String getOfficeName() {
    return get("OfficeName");
  }

  public String getPointCode() {
    return get("PointCode");
  }

  public String getPOINT() {
    return get("POINT");
  }

  public String getCEPERSONCODE() {
    return get("CEPERSONCODE");
  }

  public String getCEPERSONNAME() {
    return get("CEPERSONNAME");
  }

  public String getREQTYPECODE() {
    return get("REQTYPECODE");
  }

  public String getREQTYPE() {
    return get("REQTYPE");
  }

  public String getCREDITNAME() {
    return get("CREDITNAME");
  }

  public String getCREDITCURRENCY() {
    return get("CREDITCURRENCY");
  }

  public String getCLIENTTYPE() {
    return get("CLIENTTYPE");
  }

  public String getPOSITIONTYPE() {
    return get("POSITIONTYPE");
  }

  public String getPOSITIONDOC() {
    return get("POSITIONDOC");
  }

  public String getCURWORKEXPDOC() {
    return get("CURWORKEXPDOC");
  }

  public String getFULLEXPY() {
    return get("FULLEXPY");
  }

  public String getFULLEXPM() {
    return get("FULLEXPM");
  }

  public String getCURWORKEXPY() {
    return get("CURWORKEXPY");
  }

  public String getCURWORKEXPM() {
    return get("CURWORKEXPM");
  }

  public static DocumentClientModel toModel(DocumentClientDao source) {
    DocumentClientModel result = new DocumentClientModel();
    // Copying properties 
    result.set("Name", source.getName());
    result.set("BranchCode", source.getBranchCode());
    result.set("BRANCH", source.getBRANCH());
    result.set("OfficeCode", source.getOfficeCode());
    result.set("OfficeName", source.getOfficeName());
    result.set("PointCode", source.getPointCode());
    result.set("POINT", source.getPOINT());
    result.set("CEPERSONCODE", source.getCEPERSONCODE());
    result.set("CEPERSONNAME", source.getCEPERSONNAME());
    result.set("REQTYPECODE", source.getREQTYPECODE());
    result.set("REQTYPE", source.getREQTYPE());
    result.set("CREDITNAME", source.getCREDITNAME());
    result.set("CREDITCURRENCY", source.getCREDITCURRENCY());
    result.set("CLIENTTYPE", source.getCLIENTTYPE());
    result.set("POSITIONTYPE", source.getPOSITIONTYPE());
    result.set("POSITIONDOC", source.getPOSITIONDOC());
    result.set("CURWORKEXPDOC", source.getCURWORKEXPDOC());
    result.set("FULLEXPY", source.getFULLEXPY());
    result.set("FULLEXPM", source.getFULLEXPM());
    result.set("CURWORKEXPY", source.getCURWORKEXPY());
    result.set("CURWORKEXPM", source.getCURWORKEXPM());
    return result;
  }
}
