package org.metaforms.sandbox;

/*Generated by MPS */

import com.extjs.gxt.ui.client.data.BaseModel;

public class DocumentCreditCalcModel extends BaseModel {
  public DocumentCreditCalcModel() {
    set("BranchCode", "");
    set("Branch", "");
    set("OfficeCode", "");
    set("OfficeName", "");
    set("PointCode", "");
    set("Point", "");
    set("CEPersonCode", "");
    set("CEPersonName", "");
    set("ReqTypeCode", "");
    set("ReqType", "");
    set("CreditName", "");
    set("CreditCurrency", "");
    set("ClientType", "");
    set("PositionType", "");
    set("CurWorkExpDoc", "");
    set("FullExpY", "");
    set("FullExpM", "");
    set("CurWorkExpY", "");
    set("CurWorkExpM", "");
  }

  public void setBranchCode(String value) {
    set("BranchCode", value);
  }

  public void setBranch(String value) {
    set("Branch", value);
  }

  public void setOfficeCode(String value) {
    set("OfficeCode", value);
  }

  public void setOfficeName(String value) {
    set("OfficeName", value);
  }

  public void setPointCode(String value) {
    set("PointCode", value);
  }

  public void setPoint(String value) {
    set("Point", value);
  }

  public void setCEPersonCode(String value) {
    set("CEPersonCode", value);
  }

  public void setCEPersonName(String value) {
    set("CEPersonName", value);
  }

  public void setReqTypeCode(String value) {
    set("ReqTypeCode", value);
  }

  public void setReqType(String value) {
    set("ReqType", value);
  }

  public void setCreditName(String value) {
    set("CreditName", value);
  }

  public void setCreditCurrency(String value) {
    set("CreditCurrency", value);
  }

  public void setClientType(String value) {
    set("ClientType", value);
  }

  public void setPositionType(String value) {
    set("PositionType", value);
  }

  public void setCurWorkExpDoc(String value) {
    set("CurWorkExpDoc", value);
  }

  public void setFullExpY(String value) {
    set("FullExpY", value);
  }

  public void setFullExpM(String value) {
    set("FullExpM", value);
  }

  public void setCurWorkExpY(String value) {
    set("CurWorkExpY", value);
  }

  public void setCurWorkExpM(String value) {
    set("CurWorkExpM", value);
  }

  public String getBranchCode() {
    return get("BranchCode");
  }

  public String getBranch() {
    return get("Branch");
  }

  public String getOfficeCode() {
    return get("OfficeCode");
  }

  public String getOfficeName() {
    return get("OfficeName");
  }

  public String getPointCode() {
    return get("PointCode");
  }

  public String getPoint() {
    return get("Point");
  }

  public String getCEPersonCode() {
    return get("CEPersonCode");
  }

  public String getCEPersonName() {
    return get("CEPersonName");
  }

  public String getReqTypeCode() {
    return get("ReqTypeCode");
  }

  public String getReqType() {
    return get("ReqType");
  }

  public String getCreditName() {
    return get("CreditName");
  }

  public String getCreditCurrency() {
    return get("CreditCurrency");
  }

  public String getClientType() {
    return get("ClientType");
  }

  public String getPositionType() {
    return get("PositionType");
  }

  public String getCurWorkExpDoc() {
    return get("CurWorkExpDoc");
  }

  public String getFullExpY() {
    return get("FullExpY");
  }

  public String getFullExpM() {
    return get("FullExpM");
  }

  public String getCurWorkExpY() {
    return get("CurWorkExpY");
  }

  public String getCurWorkExpM() {
    return get("CurWorkExpM");
  }

  public static DocumentCreditCalcModel toModel(DocumentCreditCalcDao source) {
    DocumentCreditCalcModel result = new DocumentCreditCalcModel();
    // Copying properties 
    result.set("BranchCode", source.getBranchCode());
    result.set("Branch", source.getBranch());
    result.set("OfficeCode", source.getOfficeCode());
    result.set("OfficeName", source.getOfficeName());
    result.set("PointCode", source.getPointCode());
    result.set("Point", source.getPoint());
    result.set("CEPersonCode", source.getCEPersonCode());
    result.set("CEPersonName", source.getCEPersonName());
    result.set("ReqTypeCode", source.getReqTypeCode());
    result.set("ReqType", source.getReqType());
    result.set("CreditName", source.getCreditName());
    result.set("CreditCurrency", source.getCreditCurrency());
    result.set("ClientType", source.getClientType());
    result.set("PositionType", source.getPositionType());
    result.set("CurWorkExpDoc", source.getCurWorkExpDoc());
    result.set("FullExpY", source.getFullExpY());
    result.set("FullExpM", source.getFullExpM());
    result.set("CurWorkExpY", source.getCurWorkExpY());
    result.set("CurWorkExpM", source.getCurWorkExpM());
    return result;
  }
}
