package org.metaforms.sandbox;

/*Generated by MPS */

import org.hibernate.annotations.Entity;

@Entity
public final class DocumentCreditCalcDao {
  private String myBranchCode;
  private String myBranch;
  private String myOfficeCode;
  private String myOfficeName;
  private String myPointCode;
  private String myPoint;
  private String myCEPersonCode;
  private String myCEPersonName;
  private String myReqTypeCode;
  private String myReqType;
  private String myCreditName;
  private String myCreditCurrency;
  private String myClientType;
  private String myPositionType;
  private String myCurWorkExpDoc;
  private String myFullExpY;
  private String myFullExpM;
  private String myCurWorkExpY;
  private String myCurWorkExpM;

  public DocumentCreditCalcDao() {
  }

  public String getBranchCode() {
    return this.myBranchCode;
  }

  private void setBranchCode(String value) {
    this.myBranchCode = value;
  }

  public String getBranch() {
    return this.myBranch;
  }

  private void setBranch(String value) {
    this.myBranch = value;
  }

  public String getOfficeCode() {
    return this.myOfficeCode;
  }

  private void setOfficeCode(String value) {
    this.myOfficeCode = value;
  }

  public String getOfficeName() {
    return this.myOfficeName;
  }

  private void setOfficeName(String value) {
    this.myOfficeName = value;
  }

  public String getPointCode() {
    return this.myPointCode;
  }

  private void setPointCode(String value) {
    this.myPointCode = value;
  }

  public String getPoint() {
    return this.myPoint;
  }

  private void setPoint(String value) {
    this.myPoint = value;
  }

  public String getCEPersonCode() {
    return this.myCEPersonCode;
  }

  private void setCEPersonCode(String value) {
    this.myCEPersonCode = value;
  }

  public String getCEPersonName() {
    return this.myCEPersonName;
  }

  private void setCEPersonName(String value) {
    this.myCEPersonName = value;
  }

  public String getReqTypeCode() {
    return this.myReqTypeCode;
  }

  private void setReqTypeCode(String value) {
    this.myReqTypeCode = value;
  }

  public String getReqType() {
    return this.myReqType;
  }

  private void setReqType(String value) {
    this.myReqType = value;
  }

  public String getCreditName() {
    return this.myCreditName;
  }

  private void setCreditName(String value) {
    this.myCreditName = value;
  }

  public String getCreditCurrency() {
    return this.myCreditCurrency;
  }

  private void setCreditCurrency(String value) {
    this.myCreditCurrency = value;
  }

  public String getClientType() {
    return this.myClientType;
  }

  private void setClientType(String value) {
    this.myClientType = value;
  }

  public String getPositionType() {
    return this.myPositionType;
  }

  private void setPositionType(String value) {
    this.myPositionType = value;
  }

  public String getCurWorkExpDoc() {
    return this.myCurWorkExpDoc;
  }

  private void setCurWorkExpDoc(String value) {
    this.myCurWorkExpDoc = value;
  }

  public String getFullExpY() {
    return this.myFullExpY;
  }

  private void setFullExpY(String value) {
    this.myFullExpY = value;
  }

  public String getFullExpM() {
    return this.myFullExpM;
  }

  private void setFullExpM(String value) {
    this.myFullExpM = value;
  }

  public String getCurWorkExpY() {
    return this.myCurWorkExpY;
  }

  private void setCurWorkExpY(String value) {
    this.myCurWorkExpY = value;
  }

  public String getCurWorkExpM() {
    return this.myCurWorkExpM;
  }

  private void setCurWorkExpM(String value) {
    this.myCurWorkExpM = value;
  }
}
