package org.metaforms.sandbox;

/*Generated by MPS */

import org.hibernate.annotations.Entity;

@Entity
public final class DocumentClientDao {
  private String myName;
  private String myBranchCode;
  private String myBRANCH;
  private String myOfficeCode;
  private String myOfficeName;
  private String myPointCode;
  private String myPOINT;
  private String myCEPERSONCODE;
  private String myCEPERSONNAME;
  private String myREQTYPECODE;
  private String myREQTYPE;
  private String myCREDITNAME;
  private String myCREDITCURRENCY;
  private String myCLIENTTYPE;
  private String myPOSITIONTYPE;
  private String myPOSITIONDOC;
  private String myCURWORKEXPDOC;
  private String myFULLEXPY;
  private String myFULLEXPM;
  private String myCURWORKEXPY;
  private String myCURWORKEXPM;

  public DocumentClientDao() {
  }

  public String getName() {
    return this.myName;
  }

  private void setName(String value) {
    this.myName = value;
  }

  public String getBranchCode() {
    return this.myBranchCode;
  }

  private void setBranchCode(String value) {
    this.myBranchCode = value;
  }

  public String getBRANCH() {
    return this.myBRANCH;
  }

  private void setBRANCH(String value) {
    this.myBRANCH = value;
  }

  public String getOfficeCode() {
    return this.myOfficeCode;
  }

  private void setOfficeCode(String value) {
    this.myOfficeCode = value;
  }

  public String getOfficeName() {
    return this.myOfficeName;
  }

  private void setOfficeName(String value) {
    this.myOfficeName = value;
  }

  public String getPointCode() {
    return this.myPointCode;
  }

  private void setPointCode(String value) {
    this.myPointCode = value;
  }

  public String getPOINT() {
    return this.myPOINT;
  }

  private void setPOINT(String value) {
    this.myPOINT = value;
  }

  public String getCEPERSONCODE() {
    return this.myCEPERSONCODE;
  }

  private void setCEPERSONCODE(String value) {
    this.myCEPERSONCODE = value;
  }

  public String getCEPERSONNAME() {
    return this.myCEPERSONNAME;
  }

  private void setCEPERSONNAME(String value) {
    this.myCEPERSONNAME = value;
  }

  public String getREQTYPECODE() {
    return this.myREQTYPECODE;
  }

  private void setREQTYPECODE(String value) {
    this.myREQTYPECODE = value;
  }

  public String getREQTYPE() {
    return this.myREQTYPE;
  }

  private void setREQTYPE(String value) {
    this.myREQTYPE = value;
  }

  public String getCREDITNAME() {
    return this.myCREDITNAME;
  }

  private void setCREDITNAME(String value) {
    this.myCREDITNAME = value;
  }

  public String getCREDITCURRENCY() {
    return this.myCREDITCURRENCY;
  }

  private void setCREDITCURRENCY(String value) {
    this.myCREDITCURRENCY = value;
  }

  public String getCLIENTTYPE() {
    return this.myCLIENTTYPE;
  }

  private void setCLIENTTYPE(String value) {
    this.myCLIENTTYPE = value;
  }

  public String getPOSITIONTYPE() {
    return this.myPOSITIONTYPE;
  }

  private void setPOSITIONTYPE(String value) {
    this.myPOSITIONTYPE = value;
  }

  public String getPOSITIONDOC() {
    return this.myPOSITIONDOC;
  }

  private void setPOSITIONDOC(String value) {
    this.myPOSITIONDOC = value;
  }

  public String getCURWORKEXPDOC() {
    return this.myCURWORKEXPDOC;
  }

  private void setCURWORKEXPDOC(String value) {
    this.myCURWORKEXPDOC = value;
  }

  public String getFULLEXPY() {
    return this.myFULLEXPY;
  }

  private void setFULLEXPY(String value) {
    this.myFULLEXPY = value;
  }

  public String getFULLEXPM() {
    return this.myFULLEXPM;
  }

  private void setFULLEXPM(String value) {
    this.myFULLEXPM = value;
  }

  public String getCURWORKEXPY() {
    return this.myCURWORKEXPY;
  }

  private void setCURWORKEXPY(String value) {
    this.myCURWORKEXPY = value;
  }

  public String getCURWORKEXPM() {
    return this.myCURWORKEXPM;
  }

  private void setCURWORKEXPM(String value) {
    this.myCURWORKEXPM = value;
  }
}
