package org.metaforms.sandbox;

/*Generated by MPS */

import org.hibernate.annotations.Entity;

@Entity
public final class DocumentAdressDao {
  private String myCity;
  private String myCountry;
  private String myStreet;

  public DocumentAdressDao() {
  }

  public String getCity() {
    return this.myCity;
  }

  private void setCity(String value) {
    this.myCity = value;
  }

  public String getCountry() {
    return this.myCountry;
  }

  private void setCountry(String value) {
    this.myCountry = value;
  }

  public String getStreet() {
    return this.myStreet;
  }

  private void setStreet(String value) {
    this.myStreet = value;
  }
}
