package org.metaforms.sandbox;

/*Generated by MPS */

import com.extjs.gxt.ui.client.data.BaseModel;

public class DocumentAdressModel extends BaseModel {
  public DocumentAdressModel() {
    set("City", "");
    set("Country", "");
    set("Street", "");
  }

  public void setCity(String value) {
    set("City", value);
  }

  public void setCountry(String value) {
    set("Country", value);
  }

  public void setStreet(String value) {
    set("Street", value);
  }

  public String getCity() {
    return get("City");
  }

  public String getCountry() {
    return get("Country");
  }

  public String getStreet() {
    return get("Street");
  }

  public static DocumentAdressModel toModel(DocumentAdressDao source) {
    DocumentAdressModel result = new DocumentAdressModel();
    // Copying properties 
    result.set("City", source.getCity());
    result.set("Country", source.getCountry());
    result.set("Street", source.getStreet());
    return result;
  }
}
