package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"org.metaforms.forms.structure.CheckBoxGroup", "org.metaforms.forms.structure.CheckBoxItem", "org.metaforms.forms.structure.ContentPanel", "org.metaforms.forms.structure.DateField", "org.metaforms.forms.structure.Form", "org.metaforms.forms.structure.FormPanel", "org.metaforms.forms.structure.LabelField", "org.metaforms.forms.structure.MultiField", "org.metaforms.forms.structure.RadioGroup", "org.metaforms.forms.structure.Rule", "org.metaforms.forms.structure.TabItem", "org.metaforms.forms.structure.TabPanel", "org.metaforms.forms.structure.TablePanel", "org.metaforms.forms.structure.TextField", "org.metaforms.forms.structure.TriggerField"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 4:
        return new Form_BehaviorDescriptor();
      case 5:
        return new FormPanel_BehaviorDescriptor();
      case 12:
        return new TablePanel_BehaviorDescriptor();
      case 13:
        return new TextField_BehaviorDescriptor();
      case 3:
        return new DateField_BehaviorDescriptor();
      case 6:
        return new LabelField_BehaviorDescriptor();
      case 7:
        return new MultiField_BehaviorDescriptor();
      case 8:
        return new RadioGroup_BehaviorDescriptor();
      case 10:
        return new TabItem_BehaviorDescriptor();
      case 11:
        return new TabPanel_BehaviorDescriptor();
      case 14:
        return new TriggerField_BehaviorDescriptor();
      case 0:
        return new CheckBoxGroup_BehaviorDescriptor();
      case 1:
        return new CheckBoxItem_BehaviorDescriptor();
      case 2:
        return new ContentPanel_BehaviorDescriptor();
      case 9:
        return new Rule_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
