package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CheckBoxItem_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasLabel_BehaviorDescriptor, HasValue_BehaviorDescriptor {
  public CheckBoxItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.CheckBoxItem";
  }
}
