package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ContentPanel_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasChildren_BehaviorDescriptor, FormContainer_BehaviorDescriptor, IFormComponent_BehaviorDescriptor {
  public ContentPanel_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.ContentPanel";
  }
}
