package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DateField_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasBinding_BehaviorDescriptor, HasLabel_BehaviorDescriptor, HasWidth_BehaviorDescriptor, IFormComponent_BehaviorDescriptor {
  public DateField_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.DateField";
  }
}
