package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.metaforms.domain.behavior.HasDocumentReference_BehaviorDescriptor;
import org.metaforms.domain.behavior.HasId_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IContainer_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class Form_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor, HasDocumentReference_BehaviorDescriptor, HasId_BehaviorDescriptor, IContainer_BehaviorDescriptor {
  public Form_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.Form";
  }
}
