package org.metaforms.forms.behavior;

/*Generated by MPS */

import org.metaforms.domain.behavior.HasId_BehaviorDescriptor;

public interface IFormComponent_BehaviorDescriptor extends HasId_BehaviorDescriptor {
}
