package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LabelField_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IFormComponent_BehaviorDescriptor, HasBinding_BehaviorDescriptor, HasLabel_BehaviorDescriptor {
  public LabelField_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.LabelField";
  }
}
