package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class MultiField_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasOrientation_BehaviorDescriptor, HasLabel_BehaviorDescriptor, IFormComponent_BehaviorDescriptor {
  public MultiField_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.MultiField";
  }
}
