package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class RadioGroup_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasBinding_BehaviorDescriptor, HasQuery_BehaviorDescriptor, HasLabel_BehaviorDescriptor, IFormComponent_BehaviorDescriptor {
  public RadioGroup_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.RadioGroup";
  }
}
