package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TabItem_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasChildren_BehaviorDescriptor, HasLabel_BehaviorDescriptor {
  public TabItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.TabItem";
  }
}
