package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TablePanel_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasChildren_BehaviorDescriptor, FormContainer_BehaviorDescriptor, IFormComponent_BehaviorDescriptor {
  public TablePanel_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.TablePanel";
  }
}
