package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TabPanel_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IFormComponent_BehaviorDescriptor {
  public TabPanel_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.TabPanel";
  }
}
