package org.metaforms.forms.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TextField_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements HasBinding_BehaviorDescriptor, HasWidth_BehaviorDescriptor, HasLabel_BehaviorDescriptor, HasValue_BehaviorDescriptor, IFormComponent_BehaviorDescriptor {
  public TextField_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.metaforms.forms.structure.TextField";
  }
}
