package org.metaforms.forms.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.AbstractCellProvider;

public class CheckBoxItem_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_j7qed7_a(editorContext, node);
  }

  private EditorCell createCollection_j7qed7_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_j7qed7_a");
    editorCell.addEditorCell(this.createComponent_j7qed7_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_j7qed7_b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createComponent_j7qed7_a0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new LabelEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_j7qed7_b0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new ValueEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }
}
