package org.metaforms.forms.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class LabelField_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_c567jn_a(editorContext, node);
  }

  private EditorCell createCollection_c567jn_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_c567jn_a");
    editorCell.addEditorCell(this.createConstant_c567jn_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_c567jn_b0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_c567jn_c0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_c567jn_d0(editorContext, node));
    return editorCell;
  }

  private EditorCell createComponent_c567jn_b0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new FormComponentEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_c567jn_c0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new BindingEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_c567jn_d0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new LabelEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createConstant_c567jn_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\u041c\u0435\u0442\u043a\u0430");
    editorCell.setCellId("Constant_c567jn_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
