package org.metaforms.forms.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class RadioGroup_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_58r59g_a(editorContext, node);
  }

  private EditorCell createCollection_58r59g_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_58r59g_a");
    editorCell.addEditorCell(this.createConstant_58r59g_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_58r59g_b0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_58r59g_c0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_58r59g_d0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_58r59g_e0(editorContext, node));
    return editorCell;
  }

  private EditorCell createComponent_58r59g_b0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new FormComponentEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_58r59g_c0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new BindingEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_58r59g_d0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new LabelEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_58r59g_e0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new QueryEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createConstant_58r59g_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\u0412\u044b\u0431\u043e\u0440");
    editorCell.setCellId("Constant_58r59g_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
