package org.metaforms.forms.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class TriggerField_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_4mx1qt_a(editorContext, node);
  }

  private EditorCell createCollection_4mx1qt_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_4mx1qt_a");
    editorCell.addEditorCell(this.createConstant_4mx1qt_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_4mx1qt_b0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_4mx1qt_c0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_4mx1qt_d0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_4mx1qt_e0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_4mx1qt_f0(editorContext, node));
    return editorCell;
  }

  private EditorCell createComponent_4mx1qt_b0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new FormComponentEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_4mx1qt_c0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new BindingEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_4mx1qt_d0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new LabelEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_4mx1qt_e0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new WidthEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createComponent_4mx1qt_f0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new QueryEditor(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createConstant_4mx1qt_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\u0421\u043f\u0438\u0441\u043e\u043a");
    editorCell.setCellId("Constant_4mx1qt_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
