package org.metaforms.forms.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("org.metaforms.forms", "a92871fa-5f1a-445a-984b-c1a961bd4e82"), SModelReference.fromString("r:0cc4857e-b47d-4af5-89a1-5c5a96ca7ebb(org.metaforms.forms.intentions)"));
  }

  public void init() {
    add(new ConvertToDate_Intention(), "3825923826252029845");
    add(new CreateDefaultForm_Intention(), "6744709490419543974");
    add(new SurroundWithmultiField_Intention(), "3825923826251981506");
  }
}
